# Generated by Django 5.0.7 on 2024-08-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_chechlistitems_checklistitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitems',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklistitems_set', to='core.checklist'),
        ),
    ]
