# Generated by Django 5.1 on 2024-11-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_checklist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together=set(),
        ),
    ]
