# Generated by Django 5.1 on 2025-01-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_checklist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
